### PR TITLE
Fixed autoloading filenames, updated composer command to match the pa…

### PR DESCRIPTION
**Pull request by zakhenry**
…ttern better.

### CODE REVIEW

**Comment by zakhenry** [comment]
@artstorm as discussed, dropped autoloading so if we don't follow PSR-4 autoloading classname standards it should fail. I also updated the auth key generation command name to match the other commands.

**Comment by zakhenry** [comment]
@artstorm hmm there is issues with the build. I ran a `composer update` and from looking at the lock file it looks like it may have introduced some incompatibilies.

**Comment by artstorm** [comment]
@xiphiaz Checking it out now.

**Comment by zakhenry** [comment]
OK it looks like it is due to tymon/jwt-auth updating the namshi package 

> @smaxwellstewart  smaxwellstewart bumped namshi/jose to 5.0: tokens are now interoperable  5be7bed

https://github.com/tymondesigns/jwt-auth/compare/0.5.3...0.5.4

**Comment by artstorm** [comment]
@xiphiaz Seems like it was just bad timing. Nothing in this patch introduced incompatibilities, but it seems like one of the packages that the jwt package brings in got updated, and became incompatible with that update. So when running composer update with this patch, the new version of that package was brought in, where the class signature has changed.

Checking how to best fix now.

**Comment by zakhenry** [comment]
@artstorm yea it was a major upgrade in namshi/jose. Looks like it might have actually added support for RSA256 certificates, so maybe you can refactor the adapter away?

**Comment by artstorm** [comment]
@xiphiaz namshi/jose have had RS256 support before, we're relying on it. It was just the jwt package for Laravel that did not support handling it. And that still looks to be the same, so we still need our adapter to handle keys to be sent to namshi/jose.

**Comment by zakhenry** [comment]
@artstorm ah just as well your efforts weren't in vain!

**Comment by artstorm** [comment]
@xiphiaz I think this should be it. The build failed at the first attempt, but that was unrelated, a npm module that didn't want to download. I think the rebuild now will pass, and it should work again.

**Pull request merged**
