### PR TITLE
Updated composer to get latest Illumintate/hashing updates to resolve…

### PR DESCRIPTION
**Pull request by zakhenry**
… hhvm issues with bcrypt.

### CODE REVIEW

**Comment by zakhenry** [comment]
@artstorm this PR fixes the issue with the hashing that still exists. Fix required was https://github.com/illuminate/hashing/commit/298c421523d416be880bb3f75809e6b107b5c9ec

**Comment by artstorm** [comment]
@xiphiaz  Oh, I see. Nice!  This branch updates Lumen to 5.1.3, so I'll check into updating the fatal exception code (or test) to make sure that works as expected before merging.

One sort of related thought. As the app will run on hhvm, how about adding that as an additional php version to test in travis?

**Comment by artstorm** [comment]
@xiphiaz 

Something like this in travis.yml (also maybe wanting to test against 7.0, it's not that far away)?

```
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
```

**Comment by zakhenry** [comment]
@artstorm yea I'm looking into that issue now. From memory there was some reason why we couldn't use HHVM with travis ci - something about the version that they have is too old due to travis ci still using ubuntu 12.04

**Comment by zakhenry** [comment]
See https://github.com/spira/spira/issues/46

**Pull request merged**
