### PR TITLE
Refactored ApiResponse to use method chaining, and added transformer …

### PR DESCRIPTION
**Pull request by zakhenry**
…as a chainable method.

### CODE REVIEW

**Comment by zakhenry** [comment]
@Redjik I've merged PR #113 but I had some thoughts on how the transformer shouldn't necessarily be coupled to the`collection` and `item` methods, so I have done a minor refactor to make `transformer()` a chainable method.

Please review.

Also @artstorm for your reference this feature will require some refactoring on your social login branch when this gets into master. As PR #113 will also mean you need to refactor maybe hold off merging master into your branch until this one is approved and in master.

**Comment by artstorm** [comment]
@xiphiaz I had already merged in PR #113, though the refactoring to keep current with those changes were minimal. So I'd guess these additional changes will not be any major problems to refactor for too.

**Comment by Redjik** [comment]
Oh, I really like those constants in Response.
The only thing that disturbs me for now is createdCollection and createdItems methods.
They came from my implementation and furthermore from Responder concept.
This should be in a separate transformers, though I'can imagine how to inject those except of
1) either add these 2 methods to `EloquentModelTransformer`
2) or inject tranformers on per action basis (not in constructor)

**Comment by zakhenry** [comment]
@Redjik you raise a good point - I'm not entirely comfortable with setting the fields to not visible in the response; you are right that it is a transformer concern.

I think injecting on a per-action basis wouldn't make sense as I imagine the relationship between Model and Transformer is 1:1, having an `ArticleCreatedTransformer` feels wrong.

For now, the code is functional, so lets think on this and maybe revisit later. I'll create an issue on this repo to revisit.

**Pull request merged**
