### PR TITLE
Added ide-helper

### PR DESCRIPTION
**Pull request by zakhenry**

### CODE REVIEW

**Comment by zakhenry** [comment]
@Redjik I've made a start on this, but I can't get it to work immediately, can you please take a look?

**Comment by Redjik** [comment]
spent some time investigating
it is broken as it generates not a valid file
lumen and larval ide-helper file must be almost the same as they share the same alias principle
check these 2 files
Generated version for L5: https://gist.github.com/barryvdh/5227822 (which is good)
Generated version for Lumen: https://gist.github.com/barryvdh/be17164b0ad51f832f20 (which is not)

**Comment by zakhenry** [comment]
@Redjik Hmm that's a shame, I'm not sure I understand what the issue is - what is invalid about the files generated (I generated the files locally)? Can you raise a ticket on the https://github.com/barryvdh/laravel-ide-helper repo linking back to this PR so we can track when it is resolved.

**Comment by zakhenry** [comment]
@Redjik this feature has been fixed, please review & merge.

**Comment by Redjik** [comment]
checked that 2-3 weeks ago, if it's in the release - it's ok

**Pull request merged**
