### PR TITLE
Feature/api transformers

### PR DESCRIPTION
**Pull request by zakhenry**

### CODE REVIEW

**Comment by zakhenry** [comment]
@artstorm I'd like to get your current progress merged into master when you get a chance to resolve the failing tests - I want to rewrite the testing workflow to use the laravel integration tests rather than postman as discussed.

**Comment by zakhenry** [comment]
@artstorm I've updated spira/feature/api-transformers with spira/master, so this pull request should be valid, however there appears to be builds failing and a conflict. Can you please look into this?

**Comment by artstorm** [comment]
I'll look into that and see what the problem is.

**Comment by artstorm** [comment]
@xiphiaz For the failing builds, it seems to be related to bower. Checking the log for those fails, the build stops at: 'The command "gulp bower:install" failed 3 times.'.

I'd guess that might have been some temporary problem?

If I run the branch locally, with phpunit or using gulp test, all php tests passes, so I guess maybe it's just the bower won't install that is the build issue? Maybe can just rerun those failing tests, and see if they pass a second time?

**Comment by zakhenry** [comment]
@artstorm Yea that test can probably be resolved by a rerun (i've requested a restart now), but travis is reporting that the merge will have conflicts.

**Comment by zakhenry** [comment]
@artstorm ok the build failure is actually due to an issue with bower resolver. I'll fix that up and get it merged back into spira/feature/api-transformers

**Comment by zakhenry** [comment]
@artstorm I'm not sure what is going on with github, it seems to not be picking up the updated destination branch. I'm going to close and reopen this pull request.

**Comment by zakhenry** [comment]
@artstorm I'm confused. There seems to be an issue with this pull request not getting the updates from spira/master into spira/feature/api-transformers. The network diagram (below) is clearly showing that the update has occurred. And Travis CI is reporting a successful build. https://travis-ci.org/spira/spira/builds/67149659. Any ideas how to resolve this?

screen shot 2015-06-17 at 5 33 28 pm

**Comment by artstorm** [comment]
Let me pull the latest master from upstream (spira/spira) and merge that into my fork and branch, then I would assume it should not be any merge conflict.

**Comment by artstorm** [comment]
ah, I see the conflict is when merging to 'spira:feature/api-transformers'. That one might be behind enough that it needs some manual love. I believe you added me to the spira/spira repo(?), so I'll look into merging it from here, and see what manual thing that might be required.

**Comment by artstorm** [comment]
@xiphiaz Okay, merged and pushed. I'm not sure why it couldn't merge automatically before, there were no conflict when merging from command line. Anyway, should be fine now.

**Comment by zakhenry** [comment]
@artstorm ok, cool we got there at last thank you. I'll review these changes tomorrow morning.

**Pull request merged**
